<div class="popup" data-popup="popup-1">
    <div class="popup-inner">
        <h2><?php echo $this->__('Popup Title.') ?></h2>
        <p><?php echo $this->__('Write your popup alert here.') ?></p>
        <br />
        <br />
        <p><a data-popup-close="popup-1" href="#"><?php echo $this->__('Close') ?></a></p>
        <a class="popup-close" data-popup-close="popup-1" href="#">x</a>
    </div>
</div>